# networks:
#   chain-portal-network:
#     driver: bridge

services:
  angular-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:81"
    restart: always
    # networks:
    #   - chain-portal-network
