networks:
  chain-portal-network:
    driver: bridge

services:
  angular-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "45645646456:80"
    restart: always
    networks:
      - chain-portal-network
